name = "";
hide_name = false;
font = obj_ram.font;
inst = -1;
cmds[1] = "Item#Use#New Kid";
cmds[0] = "Look#Talk#Take";
x_pos = 0;
y_pos = 0;
ani_count = 0; ani_wait = 10;
ani_frame = 0;
state = 0;
list_obj = scr_open(obj_ui_list);
text_obj = scr_open(obj_msg);
depth = -300;
close = false;
char = obj_ram.char;
shade = false;
actor = -1;
delay = false;
font_wnd = obj_ram.font_wnd;
txt_wnd = scr_draw_menu(5, 1);
close2 = false;
pos = 0;
prefix = "";
target_name = "";
cmd = "";
cover = false;
dsp_cover = 0;
fx_baw = fx_create("_filter_greyscale");
fx_set_parameter(fx_baw, "g_Intensity", 1);

fow = false;