state = 0;
font = obj_ram.font;
font_wnd = obj_ram.font_wnd2;
offset_x = 0; offset_y = 0;
box_x = 0; box_y = 0;
dsp_w = 0; w = 2;
tl = obj_ram.tl;
tr = obj_ram.tr;
bl = obj_ram.bl;
br = obj_ram.br;
h = 1;
open_update = false;
close_update = false;
cursor_update = false;
select_update = false;
shift_press = false;
page_update = true;
cx = offset_x + 8;
cy = offset_y + 16;
pos = 0; last_pos = 0;
ani_frame = 0;
ani_count = 0; ani_wait = 10;
txt_wnd = "";
txt = "";
display = false;
title = "";
tx = 8; ty = 0;
page = 0;
pages = 0;
last_menu = -1;
cursor = true;
mode = 0;
move_count = 0; move_dist = 8;
move_speed = 8; move_dir = "down";
layer_gray = false;
txt2 = "";
in_btl = (room == rm_btl);
cursor_dir = 0;
cursor_wrap = true;
cursor_edge = false;
can_scroll = false;
scroll_delay = 0;
txt_offset_x = 0;
txt_offset_y = 0;
move_x = 0;
move_y = 0;